const $ = selector => document.querySelector(selector);
const projectsKey = 'framelab-projects-v2';
const configKey = 'framelab-api-config';
const currentKey = 'framelab-current-project';
const defaultConfig = { provider: 'banana', banana: { baseUrl: 'https://grsai.dakka.com.cn', key: '', model: 'nano-banana-2' }, chatgpt: { baseUrl: 'https://grsai.dakka.com.cn', key: '', model: 'gpt-image-2' } };
const demoUrls = ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=85'];
let config = { ...defaultConfig, ...JSON.parse(localStorage.getItem(configKey) || '{}') };
let provider = config.provider || 'banana';
let referenceImages = [];
let activeFilter = 'all';
let activeSort = 'newest';
let projectsCache = null;
let projectsReady = false;

function now() { return new Date().toISOString(); }
function dateLabel(date) { const value = new Date(date); return `${value.getMonth() + 1}月${String(value.getDate()).padStart(2, '0')}日 ${String(value.getHours()).padStart(2, '0')}:${String(value.getMinutes()).padStart(2, '0')}`; }
function newId() { return `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function seededProjects() { const names = ['夏日气氛实验', '未命名草稿', '毛绒角色设定', 'IP 形象探索', '产品结构灵感', '春日花园']; const time = Date.now(); return names.map((name, index) => ({ id: newId(), name, updatedAt: new Date(time - index * 86400000 * 4).toISOString(), cover: demoUrls[index], images: index === 1 ? [] : [{ id: newId(), url: demoUrls[index], createdAt: new Date(time - index * 86400000 * 4).toISOString(), referenceCount: index % 2 }] })); }
async function projects() { if (projectsReady && projectsCache) return projectsCache; try { const r = await fetch('/api/projects'); const saved = await r.json(); if (saved && saved.length) { projectsCache = saved; projectsReady = true; localStorage.removeItem(projectsKey); return saved; } } catch {} const seeded = seededProjects(); projectsCache = seeded; projectsReady = true; await saveProjects(seeded); return seeded; }
async function saveProjects(list) { projectsCache = list; projectsReady = true; try { await fetch('/api/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(list) }); } catch {} }
async function activeProject() { const list = await projects(); const wanted = localStorage.getItem(currentKey); return list.find(item => item.id === wanted) || list[0]; }
async function saveActive(project) { const list = (await projects()).map(item => item.id === project.id ? project : item); await saveProjects(list); localStorage.setItem(currentKey, project.id); }
function show(id) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('active', view.id === id)); document.querySelectorAll('.nav-item').forEach(button => button.classList.toggle('active', button.dataset.view === id)); window.scrollTo(0, 0); }
function status(message, error = false) { const target = $('#generate-status'); target.textContent = message; target.style.color = error ? '#ff8c70' : ''; }

async function renderProjects() { const grid = $('#project-grid'), template = $('#project-template'); grid.innerHTML = ''; (await projects()).sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt)).forEach(project => { const item = template.content.cloneNode(true); const card = item.querySelector('.project-card'); const image = item.querySelector('img'); image.src = project.cover || ''; image.alt = project.name; item.querySelector('.project-date').textContent = dateLabel(project.updatedAt); item.querySelector('h2').textContent = project.name; card.addEventListener('click', event => { if (!event.target.closest('.project-more, .project-menu')) openProject(project.id); }); const more = item.querySelector('.project-more'); const menu = item.querySelector('.project-menu'); more.addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); document.querySelectorAll('.project-menu.open').forEach(open => { if (open !== menu) { open.classList.remove('open'); open.closest('.project-card')?.classList.remove('menu-open'); } }); menu.classList.toggle('open'); card.classList.toggle('menu-open', menu.classList.contains('open')); }); item.querySelector('.rename-project').addEventListener('click', async event => { event.preventDefault(); event.stopPropagation(); const name = prompt('请输入项目名称', project.name); if (name && name.trim()) { project.name = name.trim(); await saveActive(project); renderProjects(); renderWorkspace(); } }); item.querySelector('.delete-project').addEventListener('click', async event => { event.preventDefault(); event.stopPropagation(); if (confirm(`删除"${project.name}"及其全部生成记录？`)) { const remaining = (await projects()).filter(item => item.id !== project.id); if (!remaining.length) remaining.push({ id: newId(), name: '未命名项目', updatedAt: now(), cover: '', images: [] }); saveProjects(remaining); if (localStorage.getItem(currentKey) === project.id) localStorage.setItem(currentKey, remaining[0].id); renderProjects(); } }); grid.append(item); }); }
async function openProject(id) { localStorage.setItem(currentKey, id); await renderWorkspace(); show('create'); }
async function visibleImages(project) { let list = [...project.images]; if (activeFilter === 'reference') list = list.filter(image => image.referenceCount > 0); if (activeFilter === 'no-reference') list = list.filter(image => !image.referenceCount); return list.sort((a, b) => activeSort === 'newest' ? new Date(b.createdAt) - new Date(a.createdAt) : new Date(a.createdAt) - new Date(b.createdAt)); }
function download(url) { const link = document.createElement('a'); link.href = url; link.download = `framelab-${Date.now()}.png`; link.target = '_blank'; link.click(); }
function openModal(url) { $('#modal-image').src = url; $('#modal-download').href = url; $('#image-modal').classList.add('open'); $('#image-modal').setAttribute('aria-hidden', 'false'); }
async function renderHistory() { const grid = $('#history-grid'); const project = await activeProject(); grid.innerHTML = ''; (await visibleImages(project)).forEach(record => { const item = $('#history-template').content.cloneNode(true); const card = item.querySelector('.history-card'); const image = item.querySelector('img'); image.src = record.url; image.alt = '生成图像'; if (record.model) { const label = item.querySelector('.model-label'); if (label) label.textContent = record.model === 'banana' ? 'banana' : 'image2'; } card.onclick = () => openModal(record.url); item.querySelector('.image-download').onclick = event => { event.stopPropagation(); download(record.url); }; item.querySelector('.image-regenerate').onclick = event => { event.stopPropagation(); regenerateHistory(record); }; grid.append(item); }); $('#history-count').textContent = grid.children.length; }
async function renderWorkspace() { const project = await activeProject(); $('#project-title').value = project.name; await renderHistory(); }
async function regenerateHistory(record) { referenceImages = []; document.querySelectorAll('.ref-image').forEach(el => el.remove()); $('#prompt').value = record.prompt || ''; if (record.model) { $('#model').value = record.model; provider = record.model; } if (record.ratio) $('#ratio').value = record.ratio; if (record.batchCount) $('#batch-count').value = String(record.batchCount); if (record.refUrls && record.refUrls.length) { status('正在加载参考图…'); try { const loaded = await Promise.all(record.refUrls.map(async (url) => { const response = await fetch(url); const blob = await response.blob(); return new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(blob); }); })); referenceImages = loaded; loaded.forEach(src => createRefImageElement(src)); if (referenceImages.length >= 10) $('.ref-add')?.classList.add('hidden'); } catch (e) { status('参考图加载失败，请重新上传', true); } } show('create'); setTimeout(() => $('#prompt').focus(), 100); }
function addReferenceFiles(files) { const maxRef = 10; Array.from(files).filter(file => file.type.startsWith('image/')).slice(0, maxRef - referenceImages.length).forEach(file => { const reader = new FileReader(); reader.onload = () => { referenceImages.push(reader.result); createRefImageElement(reader.result); if (referenceImages.length >= maxRef) $('.ref-add')?.classList.add('hidden'); }; reader.readAsDataURL(file); }); }
function createRefImageElement(src) { const wrapper = document.createElement('div'); wrapper.className = 'ref-image'; wrapper.draggable = true; const img = document.createElement('img'); img.src = src; img.title = '拖拽排序，点击 × 删除'; const del = document.createElement('button'); del.className = 'ref-delete'; del.textContent = '×'; del.title = '移除参考图'; del.onclick = event => { event.stopPropagation(); const idx = referenceImages.indexOf(src); if (idx > -1) referenceImages.splice(idx, 1); wrapper.remove(); $('.ref-add')?.classList.remove('hidden'); }; wrapper.appendChild(img); wrapper.appendChild(del); wrapper.addEventListener('dragstart', () => { wrapper.classList.add('dragging-ref'); }); wrapper.addEventListener('dragend', () => { wrapper.classList.remove('dragging-ref'); }); wrapper.addEventListener('dragover', event => { event.preventDefault(); const dragging = $('.dragging-ref'); if (!dragging || dragging === wrapper) return; const row = $('#reference-row'); const rect = wrapper.getBoundingClientRect(); const after = event.clientX - rect.left > rect.width / 2; if (after) row.insertBefore(dragging, wrapper.nextSibling); else row.insertBefore(dragging, wrapper); }); wrapper.onclick = event => { if (event.target === img) del.click(); }; $('#reference-row').insertBefore(wrapper, $('.ref-add')); }
function reorderReferenceImages() { referenceImages = Array.from(document.querySelectorAll('#reference-row .ref-image img')).map(img => img.src); }
function aspectRatioForApi(model, ratio) { if (model === 'banana') return ratio; return ({ '1:1': '1024x1024', '16:9': '1536x1024', '21:9': '1536x1024', '9:16': '1024x1536', '4:3': '1024x1024', auto: 'auto' })[ratio] || '1024x1024'; }
function loadProvider() { const data = config[provider] || {}; $('#provider-form-title').textContent = provider === 'banana' ? 'Nano Banana Pro' : 'ChatGPT Img2'; $('#endpoint').value = data.baseUrl || defaultConfig[provider].baseUrl; $('#api-key').value = data.key || ''; $('#model-id').value = data.model || defaultConfig[provider].model; $('#model').value = provider; document.querySelectorAll('.api-card').forEach(card => card.classList.toggle('selected', card.dataset.provider === provider)); }

document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => { show(button.dataset.view); if (button.dataset.view === 'projects') renderProjects(); }));
$('#home-link').onclick = event => { event.preventDefault(); renderProjects(); show('projects'); };
$('#open-settings').onclick = () => show('settings');
$('#new-project').onclick = async () => { const project = { id: newId(), name: '未命名项目', updatedAt: now(), cover: '', images: [] }; await saveProjects([project, ...(await projects())]); await openProject(project.id); };
$('#project-title').onchange = async event => { const project = await activeProject(); project.name = event.target.value.trim() || '未命名项目'; project.updatedAt = now(); await saveActive(project); renderProjects(); };
$('#reference-input').addEventListener('change', event => addReferenceFiles(event.target.files));
['dragenter', 'dragover'].forEach(type => $('#upload-zone').addEventListener(type, event => { event.preventDefault(); $('#upload-zone').classList.add('dragging'); }));
['dragleave', 'drop'].forEach(type => $('#upload-zone').addEventListener(type, event => { event.preventDefault(); $('#upload-zone').classList.remove('dragging'); }));
$('#upload-zone').addEventListener('drop', event => addReferenceFiles(event.dataTransfer.files));
document.addEventListener('paste', event => { if (event.target.tagName === 'TEXTAREA' || event.target.tagName === 'INPUT') return; const items = event.clipboardData?.items; if (!items) return; const files = []; for (const item of items) { if (item.type.startsWith('image/')) files.push(item.getAsFile()); } if (files.length > 0) { event.preventDefault(); addReferenceFiles(files); } });
$('#model').onchange = event => { provider = event.target.value; loadProvider(); };
document.querySelectorAll('.api-card').forEach(card => card.addEventListener('click', event => { if (event.target.closest('.select-provider')) return; provider = card.dataset.provider; loadProvider(); }));
document.querySelectorAll('.select-provider').forEach(button => button.onclick = event => { event.stopPropagation(); provider = event.target.closest('.api-card').dataset.provider; loadProvider(); });
$('#toggle-key').onclick = () => { const field = $('#api-key'); field.type = field.type === 'password' ? 'text' : 'password'; $('#toggle-key').textContent = field.type === 'password' ? '显示' : '隐藏'; };
$('#api-form').onsubmit = async event => { event.preventDefault(); config.provider = provider; config[provider] = { baseUrl: $('#endpoint').value.trim(), key: $('#api-key').value.trim(), model: $('#model-id').value.trim() }; localStorage.setItem(configKey, JSON.stringify(config)); try { await fetch('/api/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(config) }); } catch {} $('#save-status').textContent = '已保存（本机 + 云端）'; setTimeout(() => { $('#save-status').textContent = '密钥已保存，换设备无需重填'; }, 2200); };
$('#filter-button').onclick = () => { $('#filter-menu').classList.toggle('open'); $('#sort-menu').classList.remove('open'); };
$('#sort-button').onclick = () => { $('#sort-menu').classList.toggle('open'); $('#filter-menu').classList.remove('open'); };
document.querySelectorAll('[data-filter]').forEach(button => button.onclick = () => { activeFilter = button.dataset.filter; $('#filter-menu').classList.remove('open'); renderHistory(); });
document.querySelectorAll('[data-sort]').forEach(button => button.onclick = () => { activeSort = button.dataset.sort; $('#sort-menu').classList.remove('open'); renderHistory(); });
document.addEventListener('click', event => { if (!event.target.closest('.workspace-tools')) document.querySelectorAll('.tool-menu.open').forEach(menu => menu.classList.remove('open')); if (!event.target.closest('.project-meta')) document.querySelectorAll('.project-menu.open').forEach(menu => { menu.classList.remove('open'); menu.closest('.project-card')?.classList.remove('menu-open'); }); });
$('#modal-close').onclick = () => $('#image-modal').classList.remove('open');
$('#image-modal').onclick = event => { if (event.target === $('#image-modal')) $('#image-modal').classList.remove('open'); };
$('#generate').onclick = async () => { const button = $('#generate'); const prompt = $('#prompt').value.trim(); const ratio = $('#ratio').value; const model = $('#model').value; const count = Number($('#batch-count').value); const active = config[model] || {}; if (!prompt) return status('请先输入提示词', true); if (!active.key) { show('settings'); return status('请先在 API 管理中保存 API Key', true); } reorderReferenceImages(); const project = await activeProject(); const projectId = project.id; const batchId = `batch-${Date.now()}-${Math.random().toString(16).slice(2,6)}`; button.innerHTML = '<span>生成中…</span><b>◌</b>'; try { const payload = { model: active.model || defaultConfig[model].model, prompt, images: referenceImages, aspectRatio: aspectRatioForApi(model, ratio), replyType: 'json' }; if (model === 'banana') payload.imageSize = $('#image-size').value; let refUrls = []; if (referenceImages.length > 0) { status('正在保存参考图…'); try { const refResults = await Promise.all(referenceImages.map(img => fetch('/api/save-reference', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ imageData: img }) }).then(r => r.json()))); refUrls = refResults.map(r => r.url); } catch (e) { refUrls = []; } } const placeholders = []; for (let i = 0; i < count; i++) { const ph = createPlaceholder(batchId, i, model); placeholders.push(ph); } status(`正在同时生成 ${count} 张图片…（可继续点击生成追加）`); button.innerHTML = '<span>生成图像</span><b>→</b>'; const generateRequests = Array.from({ length: count }, async (_, i) => { const r = await fetch('/api/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ baseUrl: active.baseUrl || defaultConfig[model].baseUrl, apiKey: active.key, payload }) }); const { taskId } = await r.json(); if (!taskId) throw new Error('提交生成任务失败'); while (true) { await new Promise(done => setTimeout(done, 3000)); const sr = await fetch(`/api/status?id=${taskId}`); const s = await sr.json(); if (s.status === 'done') return { url: s.url, index: i }; if (s.status === 'failed') throw new Error(s.error || '生成失败'); } }); generateRequests.forEach((req, i) => { req.then(async (result) => { const allProjects = await projects(); const targetProject = allProjects.find(p => p.id === projectId) || allProjects[0]; const record = { id: newId(), url: result.url, createdAt: now(), referenceCount: referenceImages.length, refUrls, prompt, ratio, model, batchCount: count }; targetProject.images.unshift(record); targetProject.cover = record.url; targetProject.updatedAt = record.createdAt; await saveProjects(allProjects); replacePlaceholder(placeholders[result.index], record); renderProjects(); updatePendingCount(); status(`已生成 ${getCompletedCount()} 张，${getPendingCount()} 张进行中…`); }).catch(err => { replacePlaceholderError(placeholders[i], err.message); updatePendingCount(); }); }); } catch (error) { status(`生成失败：${error.message}`, true); } };
function createPlaceholder(batchId, index, model) { const grid = $('#history-grid'); const card = document.createElement('article'); card.className = 'history-card placeholder-card'; card.dataset.batchId = batchId; card.dataset.index = index; card.innerHTML = `<div class="placeholder-spinner"></div><span class="placeholder-label">${model === 'banana' ? 'banana' : 'image2'} #${index + 1}</span>`; grid.insertBefore(card, grid.firstChild); $('#history-count').textContent = grid.querySelectorAll('.history-card:not(.placeholder-card):not(.placeholder-error)').length; return card; }
function replacePlaceholder(placeholder, record) { if (!placeholder) return; const grid = $('#history-grid'); const item = $('#history-template').content.cloneNode(true); const card = item.querySelector('.history-card'); const image = item.querySelector('img'); image.src = record.url; image.alt = '生成图像'; const label = item.querySelector('.model-label'); if (label) label.textContent = record.model === 'banana' ? 'banana' : 'image2'; card.onclick = () => openModal(record.url); item.querySelector('.image-download').onclick = event => { event.stopPropagation(); download(record.url); }; item.querySelector('.image-regenerate').onclick = event => { event.stopPropagation(); regenerateHistory(record); }; placeholder.replaceWith(item); const cards = grid.querySelectorAll('.history-card:not(.placeholder-card):not(.placeholder-error)'); $('#history-count').textContent = cards.length; }
function replacePlaceholderError(placeholder, message) { if (!placeholder) return; placeholder.className = 'history-card placeholder-error'; placeholder.innerHTML = `<span class="placeholder-error-text">生成失败<br>${message}</span>`; }
function getPendingCount() { return document.querySelectorAll('.placeholder-card').length; }
function getCompletedCount() { const grid = $('#history-grid'); return grid.querySelectorAll('.history-card:not(.placeholder-card):not(.placeholder-error)').length; }
function updatePendingCount() { const pending = getPendingCount(); if (pending === 0) { const completed = getCompletedCount(); status(completed > 0 ? `全部完成，共 ${completed} 张图片` : '就绪'); } }
loadProvider();
window.addEventListener('DOMContentLoaded', async () => { try { const r = await fetch('/api/config'); const saved = await r.json(); if (saved && Object.keys(saved).length > 0) { config = { ...defaultConfig, ...saved }; provider = config.provider || 'banana'; localStorage.setItem(configKey, JSON.stringify(config)); loadProvider(); } } catch {} await renderProjects(); await renderWorkspace(); });
